### ISSUE TITLE
name of app?

### ISSUE THREAD

**Issue by jbenet** [ipfs/electron-app#10]
![](https://www.evernote.com/l/AMaC5-pB6xBNY7Lv9B6YYA_VSIkqRouagx4B/image.png)

maybe we should use a different name than "electron-ipfs" -- maybe "IPFS Node - Alpha" or "IPFS Node" ?

**Comment by krl** [comment]
changed to IPFS Node in #13

**Comment by jbenet** [comment]
@krl great! we should probably keep the issues open until stuff is fully merged.

**Comment by diasdavid** [comment]
The IPFS app doesn't show anymore in the dock, only in menubar. Closing this one.
