### ISSUE TITLE
osx: quiting app does not always kill ipfs

### ISSUE THREAD

**Issue by jbenet** [ipfs/electron-app#12]
go-ipfs is notoriously annoying to kill, because it tries to shut down gracefully first.

- i think `electron-app` or `node-ipfsd-ctrl` should make sure ipfs is killed by waiting + checking.
- separately, we should make go-ipfs _always_ respect sigterm. https://github.com/ipfs/go-ipfs/issues/1384

**Comment by jbenet** [comment]
another note, if the electron-app crashes (or is force quit) it doesnt also bring down the `ipfs daemon`. it looks like `ipfsd-ctl` is liberating its process child or something (i.e. normally osx will kill children when parent proc dies)

**Comment by krl** [comment]
this is now addressed in node-ipfsd-ctl, except maybe the crash issue. i'll investigate

**Comment by diasdavid** [comment]
Referenced here: https://github.com/ipfs/electron-app/issues/25#issuecomment-129768231

**Comment by diasdavid** [comment]
Fixed with https://github.com/ipfs/electron-app/commit/70efae8101b0033f78e74c9a4a9b6570f43de856 thanks to @jbenet `subcomandante` woo!
