### ISSUE TITLE
Better UX on node init

### ISSUE THREAD

**Issue by krl** [ipfs/electron-app#17]
Display a close-button and an associated platform-specific screenshot.

@jbenet, could you shoot one from osx?

**Comment by diasdavid** [comment]
@krl could you describe this a bit more?

**Comment by krl** [comment]
This was from a conversation with @jbenet, that we wanted platform specific screenshots to show users where the icon should show up in the taskbar.

**Comment by Dignifiedquire** [comment]
Done in `master`

**Comment by diasdavid** [comment]
:tada:
