### ISSUE TITLE
initialize.jsx

### ISSUE THREAD

**Issue by diasdavid** [ipfs/electron-app#24]
What is the purpose of https://github.com/ipfs/electron-app/blob/master/js/initialize.jsx ? Doesn't seem to be used, I've just removed it and tested the app again and it did everything. Could someone clarify?

**Comment by jbenet** [comment]
Isn't it used when you first install the app, when you dont have a repo?

**Comment by diasdavid** [comment]
Doesn't seem like it. I've killed+deleted everything , started it again and never saw that screen. Also can find any reference in the code that would invoke any of the code there.

**Comment by diasdavid** [comment]
my bad. got it :) 

![image](https://cloud.githubusercontent.com/assets/1211152/9083623/fde5b498-3b6b-11e5-9ce9-7242ffe362f8.png)
