### ISSUE TITLE
How to close the app, if started through the .app ?

### ISSUE THREAD

**Issue by diasdavid** [ipfs/electron-app#25]
Can't find a way to close the app, if started through the `IPFS.app`, had to kill it through Activity Monitor. Am I missing something or we don't have that yet?

**Comment by jbenet** [comment]
this thing is like a zombie

**Comment by diasdavid** [comment]
- [ ] Merge `subcomandante` into ipfsd-ctl
- [ ] Add something to the UI to quit the app

**Comment by jbenet** [comment]
@diasdavid subcomandante is now in node-ipfsd-ctl and all works well.

**Comment by diasdavid** [comment]
Done on PR https://github.com/ipfs/electron-app/pull/32
