### ISSUE TITLE
drag&drop to upload

### ISSUE THREAD

**Issue by diasdavid** [ipfs/electron-app#26]
Following: https://github.com/atom/electron/issues/2433

ref:  https://github.com/atom/electron/blob/master/docs/api/tray.md#event-drop-files

**Comment by jbenet** [comment]
sweet! :+1:

**Comment by diasdavid** [comment]
- [X] drop and upload a file to IPFS 
- [ ] drop a collection of files (needs multipart to be fixed on node-ipfs-api -> https://github.com/ipfs/node-ipfs-api/pull/35)
- [ ] make a nice UI for file upload

**Comment by whyrusleeping** [comment]
can we not use https://github.com/feross/drag-drop for this?

**Comment by diasdavid** [comment]
@whyrusleeping not quite. We want to be able to drop to the `tray icon`, which isn't an html element. 

It's working though, electron has some nice features that enable it (check drag-drop branch). Just missing a nice UI with bars and stuff spinning while it uploads (+ unicorns) and also a 'multi files' upload at the same time.

**Comment by diasdavid** [comment]
[x] Copy to the clipboard 
[x] Show on the menubar

Need to make this look good

![image](https://cloud.githubusercontent.com/assets/1211152/9153952/47c8b9f0-3e7a-11e5-83b1-749c3fbcc423.png)

**Comment by jbenet** [comment]
I'll design something tomorrow.

**Comment by diasdavid** [comment]
Thank you @jbenet :)

All the code is in this branch, the current design looks like this:
![image](https://cloud.githubusercontent.com/assets/1211152/9193442/cc591544-4013-11e5-9e94-a0414ae0945d.png)
The blue charging bar is while it uploads a file

**Comment by diasdavid** [comment]
Added multiple file upload on the branch `settings` PR -> https://github.com/ipfs/electron-app/pull/32 Let's follow all of this there
