### ISSUE TITLE
Build.sh assumes globally installed browserify

### ISSUE THREAD

**Issue by Dignifiedquire** [ipfs/electron-app#37]
Not mentioned in the readme, and let's the `npm run start` script hang. Should probably just use a local one

**Comment by harlantwood** [comment]
This should probably be fixed by changing `browserify` in [build.sh](https://github.com/ipfs/electron-app/blob/f2a547dac0accd35a38115eab9dfb4028a21dcbf/build.sh#L4-L5) to `node_modules/.bin/browserify`.

**Comment by Dignifiedquire** [comment]
agreed

**Comment by harlantwood** [comment]
PR: #38.

**Comment by diasdavid** [comment]
Thank you for catching and fixing that :)
