### ISSUE TITLE
menu bar icon on osx is huge

### ISSUE THREAD

**Issue by jbenet** [ipfs/electron-app#4]
![](https://www.evernote.com/l/AMZ0s9p76vpLQ7A5AF7PsInkQpd94-lGWg8B/image.png)

ScreenCat uses
- https://github.com/maxogden/screencat/blob/master/img/Icon.png
- https://github.com/maxogden/screencat/blob/master/app.js#L9

will need to switch based on platform, as Linux wants a large colorful icon.

**Comment by bcomnes** [comment]
http://electron.atom.io/docs/v0.27.0/api/native-image/#high-resolution-image has the details on this.

**Comment by jbenet** [comment]
we can probably do a `@2x` too
