### ISSUE TITLE
Adjusting package.json?

### ISSUE THREAD

**Issue by rabble** [ipfs/electron-app#45]
Hi,

So i went to build electron-app and i found i had to add the following to package.json to get it to build.

,
    "react": "0.13.1",
    "silence-chromium": "2.0.0",
    "indent-string": "1.2.2",
    "har-validator": "1.8.0",
    "ncp": "2.0.0",
    "nugget": "1.5.4",
    "node-uuid": "1.4.3",
    "pretty-bytes": "1.0.4",
    "shelljs": "0.4.0",
    "extract-zip": "1.1.1",
    "standard": "5.3.1",
    "mkdirp": "0.5.1",
    "electron-download": "1.1.0",
    "insert-module-globals": "6.6.0",
    "browser-pack": "5.0.1",
    "miller-rabin": "2.0.1",
    "deps-sort": "1.3.9",
    "escodegen": "1.7.0",
    "module-deps": "3.9.1",
    "sha.js": "2.4.4",
    "umd": "3.0.1",
    "browserify": "10.2.3"

But i've got next to no experience with npm so it's likely i'm doing something very wrong. But those were the additional packages i needed to get it working.

**Comment by jbenet** [comment]
did you run `npm install` at the beginning?

@diasdavid any ideas here?

**Comment by diasdavid** [comment]
@rabble which version of npm are you running? Some of the dependencies you added are dependencies of electron-app deps.

Even having to install `standard` to make it build doesn't seem right to me

**Comment by Dignifiedquire** [comment]
Should be fixed in `master`
