### ISSUE TITLE
app icon on osx is the normal electron icon

### ISSUE THREAD

**Issue by jbenet** [ipfs/electron-app#5]
![](https://www.evernote.com/l/AMY44SGUnfJFZZOh34RIPAPK2_J13YD5WR4B/image.png)

would be nice if it was the large ice IPFS logo

**Comment by bcomnes** [comment]
The dock icon requires packaging tricks iirc.  https://github.com/moose-team/friends/blob/master/pkg.js + https://github.com/moose-team/friends/blob/master/package.json#L89 are good examples of this

**Comment by krl** [comment]
this could actually have beon solved by moving the logo from dev-deps into regular deps in #9 

I cannot test macosx myself at this point

**Comment by krl** [comment]
@bcomnes We are using the very same packaging script now

**Comment by jbenet** [comment]
Actually, this looks to be fixed after using the `pkg.js` script:

![](https://www.evernote.com/l/AMaC5-pB6xBNY7Lv9B6YYA_VSIkqRouagx4B/image.png)

maybe we should use a different name than "electron-ipfs" -- maybe "IPFS Node - Alpha" or "IPFS Node" ?

**Comment by jbenet** [comment]
https://github.com/ipfs/electron-app/issues/10
